(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-project-name "ztools")
 '(jde-jdk-registry (quote (("10.0-b22" . "D:/Java/jdk1.6"))))
 '(jde-global-classpath (quote ( "E:/gits/ztools/lib/com.i3sp.build.jar" "E:/gits/ztools/lib/hamcrest-1.1.0.jar" "E:/gits/ztools/lib/junit-4.8.2.jar" "E:/gits/ztools/bin" "D:/Apache/apache-ant-1.8.2/lib/ant-antlr.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-apache-bcel.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-apache-bsf.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-apache-log4j.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-apache-oro.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-apache-regexp.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-apache-resolver.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-apache-xalan2.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-commons-logging.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-commons-net.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-jai.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-javamail.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-jdepend.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-jmf.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-jsch.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-junit.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-junit4.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-launcher.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-netrexx.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-swing.jar" "D:/Apache/apache-ant-1.8.2/lib/ant-testutil.jar" "D:/Apache/apache-ant-1.8.2/lib/ant.jar" "D:/Apache/apache-ant-1.8.2/lib/ivy.jar" "D:/Apache/apache-ant-1.8.2/lib/jsch-0.1.46.jar" "D:/eclipse/plugins/org.apache.ivy.eclipse.ant_2.2.0.final_20100923230623/ivy.jar" "D:/eclipse/configuration/org.eclipse.osgi/bundles/56/1/.cp/lib/antdebug.jar" "D:/eclipse/configuration/org.eclipse.osgi/bundles/56/1/.cp/lib/remote.jar" "D:/eclipse/configuration/org.eclipse.osgi/bundles/57/1/.cp/lib/remoteAnt.jar" "D:/Java/jdk1.6/lib/tools.jar" "D:/eclipse/plugins/org.eclipse.swt.win32.win32.x86_64_3.7.1.v3738a.jar")))
 '(jde-compile-option-sourcepath (quote ("E:/gits/ztools/src")))
 '(jde-run-working-directory "E:/gits/ztools")
 '(jde-sourcepath (quote ("E:/gits/ztools/src")))
 '(jde-compile-option-directory "E:/gits/ztools/classes") '(jde-build-function (quote (jde-ant-build)))
 '(jde-ant-enable-find t)
 '(jde-ant-user-jar-files (quote ("E:/gits/ztools/lib/com.i3sp.build.jar")))
 '(jde-ant-read-target t)
 '(jde-ant-home "D:/Apache/apache-ant-1.8.2")
 '(jde-ant-invocation-method (quote ("Ant Server")))
 )
